name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21
        with:
          determinate: false

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Checkout registry-dev
        uses: actions/checkout@v4
        with:
          repository: purescript/registry-dev
          ref: master
          path: registry-dev

      - name: Build source
        run: nix develop -c spago build

      - name: Build examples
        working-directory: example
        run: nix develop -c spago build
