name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: purescript-contrib/setup-purescript@main

      - name: Cache PureScript dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.lock') }}
          path: |
            .spago
            output

      - name: Build source
        run: spago build

      - name: Build examples
        working-directory: example
        run: spago build
